-- VCollab Supabase baseline schema.
-- Folded from Spring/Flyway V1, V3-V8, V10, with MySQL syntax converted to Postgres.

create extension if not exists pg_trgm;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email varchar(255) not null unique,
  username varchar(255) not null unique,
  password_hash varchar(255),
  role varchar(50) not null check (role in ('SUPER_ADMIN', 'STUDENT', 'INDUSTRIAL_EXPERT', 'SOFTWARE_ENGINEER')),
  is_active boolean not null default true,
  is_suspended boolean not null default false,
  email_verified boolean not null default false,
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_users_auth_user on public.users(auth_user_id);
create index idx_users_role on public.users(role);
create index idx_users_active on public.users(is_active, is_suspended);
create index idx_users_deleted_at on public.users(deleted_at);

create table public.user_profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  full_name varchar(255) not null,
  bio text,
  profile_image varchar(1024),
  cover_image varchar(1024),
  department varchar(255),
  year_of_study varchar(255),
  institution varchar(255),
  skills text,
  github_url varchar(255),
  linkedin_url varchar(255),
  website_url varchar(255),
  dob date,
  education_type varchar(20),
  institution_name varchar(255),
  grade varchar(20),
  academic_year varchar(20),
  semester varchar(20),
  faculty varchar(255),
  follower_count integer not null default 0,
  following_count integer not null default 0,
  project_count integer not null default 0,
  post_count integer not null default 0,
  blog_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create table public.categories (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  slug varchar(255) not null unique,
  type varchar(50) not null,
  is_system_default boolean not null default false,
  is_active boolean not null default true,
  created_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_categories_type_active on public.categories(type, is_active);
create index idx_categories_deleted_at on public.categories(deleted_at);

create table public.projects (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id),
  category_id bigint references public.categories(id),
  title varchar(500) not null,
  slug varchar(520) not null,
  short_desc varchar(1000),
  full_desc text,
  tech_stack text,
  tags text,
  github_url varchar(1000),
  demo_url varchar(1000),
  youtube_url varchar(1000),
  pdf_url varchar(1000),
  course_url varchar(1000),
  thumbnail varchar(1024),
  visibility varchar(50) not null default 'PUBLIC',
  is_active boolean not null default true,
  like_count integer not null default 0,
  comment_count integer not null default 0,
  save_count integer not null default 0,
  share_count integer not null default 0,
  view_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_projects_owner on public.projects(owner_id);
create index idx_projects_category on public.projects(category_id);
create index idx_projects_visibility_active on public.projects(visibility, is_active, deleted_at);
create index idx_projects_created_at on public.projects(created_at);

create table public.project_media (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  url varchar(1000) not null,
  media_type varchar(50) not null,
  file_name varchar(255),
  file_size bigint,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index idx_project_media_project on public.project_media(project_id, sort_order);

create table public.posts (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.users(id),
  category_id bigint references public.categories(id),
  content text not null,
  post_type varchar(50) not null,
  tags text,
  visibility varchar(50) not null default 'PUBLIC',
  is_active boolean not null default true,
  like_count integer not null default 0,
  comment_count integer not null default 0,
  save_count integer not null default 0,
  share_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_posts_author on public.posts(author_id);
create index idx_posts_category on public.posts(category_id);
create index idx_posts_visibility_active on public.posts(visibility, is_active, deleted_at);
create index idx_posts_created_at on public.posts(created_at);

create table public.post_media (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  url varchar(1000) not null,
  media_type varchar(50) not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index idx_post_media_post on public.post_media(post_id, sort_order);

create table public.blogs (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.users(id),
  category_id bigint references public.categories(id),
  title varchar(500) not null,
  slug varchar(520) not null,
  cover_image varchar(1024),
  content text not null,
  tags text,
  visibility varchar(50) not null default 'PUBLIC',
  is_active boolean not null default true,
  like_count integer not null default 0,
  comment_count integer not null default 0,
  save_count integer not null default 0,
  share_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_blogs_author on public.blogs(author_id);
create index idx_blogs_category on public.blogs(category_id);
create index idx_blogs_visibility_active on public.blogs(visibility, is_active, deleted_at);
create index idx_blogs_created_at on public.blogs(created_at);

create table public.blog_media (
  id bigint generated by default as identity primary key,
  blog_id bigint not null references public.blogs(id) on delete cascade,
  url varchar(1000) not null,
  media_type varchar(50) not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index idx_blog_media_blog on public.blog_media(blog_id, sort_order);

create table public.comments (
  id bigint generated by default as identity primary key,
  author_id bigint not null references public.users(id),
  content_type varchar(50) not null,
  content_id bigint not null,
  parent_id bigint references public.comments(id),
  content text not null,
  image_url varchar(1024),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_comments_content on public.comments(content_type, content_id);
create index idx_comments_author on public.comments(author_id);
create index idx_comments_parent on public.comments(parent_id);

create table public.comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (comment_id, user_id)
);

create table public.likes (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  content_type varchar(50) not null,
  content_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (user_id, content_type, content_id)
);

create index idx_likes_content on public.likes(content_type, content_id);

create table public.saves (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  content_type varchar(50) not null,
  content_id bigint not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (user_id, content_type, content_id)
);

create index idx_saves_content on public.saves(content_type, content_id);

create table public.shares (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id),
  content_type varchar(50) not null,
  content_id bigint not null,
  share_type varchar(50),
  target_url varchar(1024),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (user_id, content_type, content_id, share_type)
);

create index idx_shares_content on public.shares(content_type, content_id);

create table public.follows (
  id bigint generated by default as identity primary key,
  follower_id bigint not null references public.users(id),
  following_id bigint not null references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create index idx_follows_following on public.follows(following_id);

create table public.follow_requests (
  id bigint generated by default as identity primary key,
  requester_id bigint not null references public.users(id),
  target_id bigint not null references public.users(id),
  status varchar(50) not null default 'PENDING',
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (requester_id, target_id)
);

create table public.project_requests (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id),
  requester_id bigint not null references public.users(id),
  owner_id bigint not null references public.users(id),
  message text,
  status varchar(50) not null,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (project_id, requester_id)
);

create index idx_project_requests_owner on public.project_requests(owner_id, status);

create table public.conversations (
  id bigint generated by default as identity primary key,
  created_by bigint references public.users(id),
  last_message_id bigint,
  last_message_at timestamptz,
  is_group boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_conversations_updated_at on public.conversations(updated_at);
create index idx_conversations_last_message_at on public.conversations(last_message_at);

create table public.conversation_members (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  user_id bigint not null references public.users(id),
  last_read_at timestamptz,
  last_delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (conversation_id, user_id)
);

create index idx_conversation_members_user on public.conversation_members(user_id);

create table public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_id bigint not null references public.users(id),
  content text not null,
  message_type varchar(50) not null default 'TEXT',
  attachment_url varchar(1024),
  is_deleted boolean not null default false,
  reply_to_id bigint references public.messages(id),
  delivered_at timestamptz,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

alter table public.conversations
  add constraint fk_conversations_last_message
  foreign key (last_message_id) references public.messages(id) on delete set null;

create index idx_messages_conversation_created on public.messages(conversation_id, created_at);
create index idx_messages_sender on public.messages(sender_id);

create table public.user_presence (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.users(id) on delete cascade,
  status varchar(20) not null default 'OFFLINE',
  session_count integer not null default 0,
  last_seen_at timestamptz,
  last_heartbeat_at timestamptz,
  active_conversation_id bigint references public.conversations(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_user_presence_status_seen on public.user_presence(status, last_seen_at);

create table public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id bigint not null references public.users(id),
  actor_id bigint references public.users(id),
  type varchar(50) not null,
  content_type varchar(50),
  content_id bigint,
  message text,
  is_read boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_notifications_recipient_read on public.notifications(recipient_id, is_read, created_at);
create index idx_notifications_content on public.notifications(content_type, content_id);

create table public.reports (
  id bigint generated by default as identity primary key,
  reporter_id bigint not null references public.users(id),
  content_type varchar(50) not null,
  content_id bigint not null,
  reason varchar(50) not null,
  description text,
  status varchar(50) not null,
  admin_note text,
  resolved_by bigint references public.users(id),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_reports_status_created on public.reports(status, created_at);
create index idx_reports_content on public.reports(content_type, content_id);

create table public.warnings (
  id bigint generated by default as identity primary key,
  target_user_id bigint not null references public.users(id),
  content_type varchar(50),
  content_id bigint,
  title varchar(255) not null,
  message text not null,
  reason text,
  status varchar(50) not null,
  acknowledged_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_warnings_target_status on public.warnings(target_user_id, status);

create table public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.users(id),
  module_name varchar(100) not null,
  action_name varchar(100) not null,
  target_type varchar(100),
  target_id bigint,
  summary varchar(500),
  metadata text,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_audit_logs_module_action on public.audit_logs(module_name, action_name, created_at);
create index idx_audit_logs_target on public.audit_logs(target_type, target_id);

create table public.cms_blocks (
  id bigint generated by default as identity primary key,
  section_key varchar(100) not null,
  title varchar(200) not null,
  subtitle varchar(400),
  body text not null,
  badge varchar(120),
  cta_label varchar(120),
  cta_url varchar(400),
  theme_tone varchar(60),
  display_order integer not null default 0,
  is_active boolean not null default true,
  is_public_visible boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_cms_blocks_section_order on public.cms_blocks(section_key, display_order);
create index idx_cms_blocks_public on public.cms_blocks(is_active, is_public_visible, deleted_at);

create table public.content_targeting (
  id bigint generated by default as identity primary key,
  content_id bigint not null,
  content_type varchar(20) not null,
  target_type varchar(20) not null default 'ALL',
  grade varchar(20),
  academic_year varchar(20),
  semester varchar(20),
  faculty varchar(255),
  institution_name varchar(255),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (content_id, content_type)
);

create index idx_ct_target_type on public.content_targeting(target_type);
create index idx_ct_grade on public.content_targeting(grade);
create index idx_ct_academic_year on public.content_targeting(academic_year);
create index idx_ct_institution on public.content_targeting(institution_name);

create table public.system_tags (
  id bigint generated by default as identity primary key,
  tag_name varchar(100) not null unique,
  tag_type varchar(20) not null default 'SYSTEM',
  label varchar(255),
  mapped_attribute text,
  icon varchar(50),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_system_tags_search on public.system_tags using gin ((tag_name || ' ' || coalesce(label, '')) gin_trgm_ops);

create table public.shareable_links (
  id bigint generated by default as identity primary key,
  content_type varchar(50) not null,
  content_id bigint not null,
  token varchar(128) not null unique,
  created_by bigint not null references public.users(id),
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create table public.resource_categories (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  slug varchar(140) not null unique,
  description varchar(255),
  icon varchar(80),
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_resource_categories_active on public.resource_categories(active, sort_order);

create table public.resource_folders (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.resource_folders(id),
  owner_id bigint references public.users(id),
  category_id bigint references public.resource_categories(id),
  name varchar(180) not null,
  slug varchar(220) not null,
  folder_type varchar(40) not null,
  visibility varchar(30) not null default 'PUBLIC',
  active boolean not null default true,
  system_generated boolean not null default false,
  sort_order integer not null default 0,
  tree_path varchar(1000) not null default '',
  depth integer not null default 0,
  institution_name varchar(180),
  academic_year_label varchar(120),
  semester_label varchar(120),
  module_name varchar(180),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_resource_folders_parent on public.resource_folders(parent_id, active, deleted_at);
create index idx_resource_folders_owner on public.resource_folders(owner_id, active, deleted_at);
create index idx_resource_folders_type on public.resource_folders(folder_type, active, deleted_at);
create index idx_resource_folders_tree on public.resource_folders(tree_path);
create index idx_resource_folders_academic on public.resource_folders(institution_name, academic_year_label, semester_label);
create unique index uq_resource_folders_parent_slug_live on public.resource_folders(coalesce(parent_id, 0), slug) where deleted_at is null;

create table public.resource_files (
  id bigint generated by default as identity primary key,
  folder_id bigint not null references public.resource_folders(id),
  owner_id bigint not null references public.users(id),
  display_name varchar(220) not null,
  original_file_name varchar(255) not null,
  stored_file_name varchar(255) not null,
  storage_path varchar(500) not null,
  public_url varchar(500) not null,
  mime_type varchar(160) not null,
  extension varchar(20) not null,
  resource_type varchar(40) not null,
  file_size bigint not null,
  visibility varchar(30) not null default 'PUBLIC',
  active boolean not null default true,
  allow_download boolean not null default true,
  institution_name varchar(180),
  academic_year_label varchar(120),
  semester_label varchar(120),
  category_name varchar(180),
  module_name varchar(180),
  sub_category_name varchar(180),
  subject_code varchar(80),
  academic_batch varchar(120),
  lecturer_name varchar(180),
  description text,
  tags_text text,
  view_count integer not null default 0,
  download_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create index idx_resource_files_folder on public.resource_files(folder_id, active, deleted_at);
create index idx_resource_files_owner on public.resource_files(owner_id, active, deleted_at);
create index idx_resource_files_visibility on public.resource_files(visibility, active, deleted_at);
create index idx_resource_files_recent on public.resource_files(created_at, deleted_at);
create index idx_resource_files_downloads on public.resource_files(download_count, deleted_at);
create index idx_resource_files_views on public.resource_files(view_count, deleted_at);
create index idx_resource_files_academic on public.resource_files(institution_name, academic_year_label, semester_label, category_name);

create table public.platform_feature_settings (
  id bigint generated by default as identity primary key,
  feature_key varchar(100) not null unique,
  mode varchar(50) not null,
  config_json jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id)
);

create table public.v_hub_threads (
  id bigint generated by default as identity primary key,
  author_id bigint references public.users(id),
  guest_name varchar(120),
  guest_email varchar(180),
  title varchar(180) not null,
  body text not null,
  thread_type varchar(50) not null,
  status varchar(50) not null,
  tags text,
  is_locked boolean not null default false,
  is_hidden boolean not null default false,
  best_reply_id bigint,
  reply_count integer not null default 0,
  participant_count integer not null default 0,
  view_count integer not null default 0,
  last_activity_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  check (author_id is not null or guest_name is not null)
);

create index idx_v_hub_threads_author on public.v_hub_threads(author_id);
create index idx_v_hub_threads_type_status on public.v_hub_threads(thread_type, status, is_hidden);
create index idx_v_hub_threads_last_activity on public.v_hub_threads(last_activity_at);
create index idx_v_hub_threads_deleted_at on public.v_hub_threads(deleted_at);
create index idx_v_hub_threads_guest_name on public.v_hub_threads(guest_name);

create table public.v_hub_replies (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.v_hub_threads(id) on delete cascade,
  author_id bigint references public.users(id),
  guest_name varchar(120),
  guest_email varchar(180),
  parent_reply_id bigint references public.v_hub_replies(id),
  body text not null,
  is_best_answer boolean not null default false,
  is_hidden boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  check (author_id is not null or guest_name is not null)
);

alter table public.v_hub_threads
  add constraint fk_v_hub_threads_best_reply
  foreign key (best_reply_id) references public.v_hub_replies(id) on delete set null;

create index idx_v_hub_replies_thread_created on public.v_hub_replies(thread_id, created_at);
create index idx_v_hub_replies_author on public.v_hub_replies(author_id);
create index idx_v_hub_replies_parent on public.v_hub_replies(parent_reply_id);
create index idx_v_hub_replies_deleted_at on public.v_hub_replies(deleted_at);
create index idx_v_hub_replies_guest_name on public.v_hub_replies(guest_name);

create table public.v_hub_thread_participants (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.v_hub_threads(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  last_read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  deleted_at timestamptz,
  deleted_by bigint references public.users(id),
  unique (thread_id, user_id)
);

create index idx_v_hub_thread_participants_user on public.v_hub_thread_participants(user_id, updated_at);
create index idx_v_hub_thread_participants_deleted_at on public.v_hub_thread_participants(deleted_at);

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'users', 'user_profiles', 'categories', 'projects', 'posts', 'blogs', 'comments',
    'likes', 'saves', 'shares', 'follows', 'follow_requests', 'project_requests',
    'conversations', 'conversation_members', 'messages', 'user_presence', 'notifications',
    'reports', 'warnings', 'audit_logs', 'cms_blocks', 'content_targeting', 'system_tags',
    'shareable_links', 'resource_categories', 'resource_folders', 'resource_files',
    'platform_feature_settings', 'v_hub_threads', 'v_hub_replies', 'v_hub_thread_participants'
  ]
  loop
    execute format('create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()', table_name, table_name);
  end loop;
end $$;
